services:
  ms-segip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-segip
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    # Si el host requiere utilizar el DNS interno institucional para resolver segip-api.fiscalia.gob.bo
    # dns:
    #   - 192.168.20.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
